name: Build and deploy ASP.Net Core app to Azure Web App - app-mesa-inventarios-api-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Clean solution
        run: dotnet clean

      - name: Delete bin and obj
        run: |
          find . -type d -name "bin" -exec rm -rf {} +
          find . -type d -name "obj" -exec rm -rf {} +

      - name: Restore
        run: dotnet restore ./API/API.csproj

      - name: Build
        run: dotnet build ./API/API.csproj -c Release --no-restore

      - name: Clean publish folder
        run: rm -rf ./publish

      - name: Publish
        run: dotnet publish ./API/API.csproj -c Release -o ./publish --no-build
        
      - name: Verify runtime files
        run: |
          echo "==== runtimeconfig ===="
          ls ./publish/*.runtimeconfig.json || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./publish

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-mesa-inventarios-api-prod'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7D5A8EA7DFDF4D36AF831E5A7C22456B }}
          package: ./publish
